-- altering table column types
ALTER TABLE Provider_LOS RENAME COLUMN Avg_LOS to LOS;


-- change data type from double to int for relevant columns
ALTER TABLE EMS ALTER Is_EMS TYPE INTEGER;
ALTER TABLE EMS ALTER Means_Of_Arrival_CD TYPE INTEGER;
ALTER TABLE ENCOUNTER ALTER Age TYPE INTEGER;
ALTER TABLE ENCOUNTER ALTER Means_Of_Arrival_CD TYPE INTEGER;
ALTER TABLE ENCOUNTER ALTER PAT_ENC_CSN_ID TYPE INTEGER;
ALTER TABLE Provider_LOS ALTER "Year" TYPE INTEGER;
ALTER TABLE Provider_LOS ALTER "Month" TYPE INTEGER;
