.append stg_ordered_flat <| func_ordered_flat();

raw_ordered
| take 100
| where tostring(payload.op) in ("r", "c", "u", "d")

.delete table raw_ordered records <|
    raw_ordered
    | where tostring(payload.op) in ("r", "c", "u", "d")
    | where unixtime_milliseconds_todatetime(tolong(payload.after.LastModified)) < ago(336h)

stg_ordered_flat
| take 100
| where CDCOperation in ("r", "c", "u", "d")
| sort by LastModified desc 

-- stg_ordered_flat currently 47889
-- raw_ordered currently 47859